// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: protos/msg.proto

package p

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Result struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Response:
	//
	//	*Result_GETRes
	Response      isResult_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_protos_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_protos_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_protos_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Result) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Result) GetResponse() isResult_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *Result) GetGETRes() *GETRes {
	if x != nil {
		if x, ok := x.Response.(*Result_GETRes); ok {
			return x.GETRes
		}
	}
	return nil
}

type isResult_Response interface {
	isResult_Response()
}

type Result_GETRes struct {
	GETRes *GETRes `protobuf:"bytes,11,opt,name=GETRes,proto3,oneof"`
}

func (*Result_GETRes) isResult_Response() {}

type GETRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GETRes) Reset() {
	*x = GETRes{}
	mi := &file_protos_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GETRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GETRes) ProtoMessage() {}

func (x *GETRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GETRes.ProtoReflect.Descriptor instead.
func (*GETRes) Descriptor() ([]byte, []int) {
	return file_protos_msg_proto_rawDescGZIP(), []int{1}
}

func (x *GETRes) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_protos_msg_proto protoreflect.FileDescriptor

var file_protos_msg_proto_rawDesc = string([]byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x01, 0x70, 0x22, 0x53, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x23, 0x0a, 0x06, 0x47, 0x45, 0x54,
	0x52, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x2e, 0x47, 0x45,
	0x54, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x06, 0x47, 0x45, 0x54, 0x52, 0x65, 0x73, 0x42, 0x0a,
	0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x0a, 0x06, 0x47, 0x45,
	0x54, 0x52, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x05, 0x5a, 0x03, 0x2e, 0x2f,
	0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_protos_msg_proto_rawDescOnce sync.Once
	file_protos_msg_proto_rawDescData []byte
)

func file_protos_msg_proto_rawDescGZIP() []byte {
	file_protos_msg_proto_rawDescOnce.Do(func() {
		file_protos_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_msg_proto_rawDesc), len(file_protos_msg_proto_rawDesc)))
	})
	return file_protos_msg_proto_rawDescData
}

var file_protos_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_msg_proto_goTypes = []any{
	(*Result)(nil), // 0: p.Result
	(*GETRes)(nil), // 1: p.GETRes
}
var file_protos_msg_proto_depIdxs = []int32{
	1, // 0: p.Result.GETRes:type_name -> p.GETRes
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_msg_proto_init() }
func file_protos_msg_proto_init() {
	if File_protos_msg_proto != nil {
		return
	}
	file_protos_msg_proto_msgTypes[0].OneofWrappers = []any{
		(*Result_GETRes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_msg_proto_rawDesc), len(file_protos_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_msg_proto_goTypes,
		DependencyIndexes: file_protos_msg_proto_depIdxs,
		MessageInfos:      file_protos_msg_proto_msgTypes,
	}.Build()
	File_protos_msg_proto = out.File
	file_protos_msg_proto_goTypes = nil
	file_protos_msg_proto_depIdxs = nil
}
